-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 13:17:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TAW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TAW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TAW` ;
USE `TAW` ;

-- -----------------------------------------------------
-- Table `TAW`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`ROL` ;

CREATE TABLE IF NOT EXISTS `TAW`.`ROL` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`rol_id`));


-- -----------------------------------------------------
-- Table `TAW`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `TAW`.`CATEGORIA` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoria_id`));


-- -----------------------------------------------------
-- Table `TAW`.`GRUPO_MUSCULAR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`GRUPO_MUSCULAR` ;

CREATE TABLE IF NOT EXISTS `TAW`.`GRUPO_MUSCULAR` (
  `grupo_muscular_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`grupo_muscular_id`));


-- -----------------------------------------------------
-- Table `TAW`.`ALIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`ALIMENTO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`ALIMENTO` (
  `alimento_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `calorias_por_gramo` INT NOT NULL,
  PRIMARY KEY (`alimento_id`));


-- -----------------------------------------------------
-- Table `TAW`.`EJERCICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`EJERCICIO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`EJERCICIO` (
  `ejercicio_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `url_video` VARCHAR(255) NOT NULL,
  `grupo_muscular_id` INT NULL DEFAULT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ejercicio_id`),
  INDEX `grupo_muscular_fk` (`grupo_muscular_id` ASC) VISIBLE,
  INDEX `m_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `grupo_muscular_fk`
    FOREIGN KEY (`grupo_muscular_id`)
    REFERENCES `TAW`.`GRUPO_MUSCULAR` (`grupo_muscular_id`),
  CONSTRAINT `categoria_fk`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `TAW`.`CATEGORIA` (`categoria_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `TAW`.`TIPO_RUTINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`TIPO_RUTINA` ;

CREATE TABLE IF NOT EXISTS `TAW`.`TIPO_RUTINA` (
  `tipo_rutina_id` INT NOT NULL,
  `tipo_rutina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_rutina_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAW`.`RUTINA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`RUTINA` ;

CREATE TABLE IF NOT EXISTS `TAW`.`RUTINA` (
  `rutina_id` INT NOT NULL AUTO_INCREMENT,
  `entrenador_id` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipo_rutina_id` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`rutina_id`),
  INDEX `entrenador_fk` (`entrenador_id` ASC) VISIBLE,
  INDEX `tipo_rutina_id_idx` (`tipo_rutina_id` ASC) VISIBLE,
  CONSTRAINT `entrenador_fk`
    FOREIGN KEY (`entrenador_id`)
    REFERENCES `TAW`.`USUARIO` (`usuario_id`),
  CONSTRAINT `tipo_rutina_fk`
    FOREIGN KEY (`tipo_rutina_id`)
    REFERENCES `TAW`.`TIPO_RUTINA` (`tipo_rutina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TAW`.`DIETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`DIETA` ;

CREATE TABLE IF NOT EXISTS `TAW`.`DIETA` (
  `dieta_id` INT NOT NULL AUTO_INCREMENT,
  `dietista_id` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `feedback` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`dieta_id`),
  INDEX `dietista_fk` (`dietista_id` ASC) VISIBLE,
  CONSTRAINT `dietista_fk`
    FOREIGN KEY (`dietista_id`)
    REFERENCES `TAW`.`USUARIO` (`usuario_id`));


-- -----------------------------------------------------
-- Table `TAW`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`USUARIO` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `peso` INT NULL DEFAULT NULL,
  `altura` INT NULL DEFAULT NULL,
  `edad` INT NULL DEFAULT NULL,
  `rol_id` INT NULL DEFAULT NULL,
  `rutina_id` INT NULL,
  `dieta_id` INT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `rol_fk` (`rol_id` ASC) VISIBLE,
  INDEX `rutina_id_fk_idx` (`rutina_id` ASC) VISIBLE,
  INDEX `dieta_id_fk_idx` (`dieta_id` ASC) VISIBLE,
  CONSTRAINT `rol_fk`
    FOREIGN KEY (`rol_id`)
    REFERENCES `TAW`.`ROL` (`rol_id`),
  CONSTRAINT `rutina_fk`
    FOREIGN KEY (`rutina_id`)
    REFERENCES `TAW`.`RUTINA` (`rutina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dieta_fk`
    FOREIGN KEY (`dieta_id`)
    REFERENCES `TAW`.`DIETA` (`dieta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `TAW`.`MENU_DIARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`MENU_DIARIO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`MENU_DIARIO` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` INT NOT NULL,
  `dieta_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`),
  CONSTRAINT `dieta_fk_menu`
    FOREIGN KEY (`dieta_id`)
    REFERENCES `TAW`.`DIETA` (`dieta_id`));


-- -----------------------------------------------------
-- Table `TAW`.`SESION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`SESION` ;

CREATE TABLE IF NOT EXISTS `TAW`.`SESION` (
  `sesion_id` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` INT NOT NULL,
  `rutina_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sesion_id`),
  INDEX `rutina_fk_sesion` (`rutina_id` ASC) VISIBLE,
  CONSTRAINT `rutina_fk_sesion`
    FOREIGN KEY (`rutina_id`)
    REFERENCES `TAW`.`RUTINA` (`rutina_id`));


-- -----------------------------------------------------
-- Table `TAW`.`INGESTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`INGESTAS` ;

CREATE TABLE IF NOT EXISTS `TAW`.`INGESTAS` (
  `ingestas_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `gramos_recomendados` INT NULL DEFAULT NULL,
  `calorias_recomendadas` INT NULL DEFAULT NULL,
  `menu_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ingestas_id`),
  INDEX `menu_diario_fk` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `menu_diario_fk`
    FOREIGN KEY (`menu_id`)
    REFERENCES `TAW`.`MENU_DIARIO` (`menu_id`));


-- -----------------------------------------------------
-- Table `TAW`.`SESIONEJERCICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`SESIONEJERCICIO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`SESIONEJERCICIO` (
  `sesion_ejercicio_id` INT NOT NULL AUTO_INCREMENT,
  `sesion_id` INT NULL DEFAULT NULL,
  `ejercicio_id` INT NULL DEFAULT NULL,
  `numero_ejercicio` INT NOT NULL,
  PRIMARY KEY (`sesion_ejercicio_id`),
  INDEX `sesion_fk` (`sesion_id` ASC) VISIBLE,
  INDEX `ejercicio_fk` (`ejercicio_id` ASC) VISIBLE,
  CONSTRAINT `sesion_fk`
    FOREIGN KEY (`sesion_id`)
    REFERENCES `TAW`.`SESION` (`sesion_id`),
  CONSTRAINT `ejercicio_fk`
    FOREIGN KEY (`ejercicio_id`)
    REFERENCES `TAW`.`EJERCICIO` (`ejercicio_id`));


-- -----------------------------------------------------
-- Table `TAW`.`INGESTAALIMENTOUSUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`INGESTAALIMENTOUSUARIO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`INGESTAALIMENTOUSUARIO` (
  `usuario_id` INT NOT NULL,
  `alimento_id` INT NOT NULL,
  `ingestas_id` INT NOT NULL,
  `gramos_consumidos` INT NULL DEFAULT NULL,
  `calorias_consumidos` INT NULL DEFAULT NULL,
  `feedback` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`usuario_id`, `alimento_id`, `ingestas_id`),
  INDEX `alimento_fk` (`alimento_id` ASC) VISIBLE,
  INDEX `ingesta_fk` (`ingestas_id` ASC) VISIBLE,
  CONSTRAINT `usuario_fk`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `TAW`.`USUARIO` (`usuario_id`),
  CONSTRAINT `alimento_fk`
    FOREIGN KEY (`alimento_id`)
    REFERENCES `TAW`.`ALIMENTO` (`alimento_id`),
  CONSTRAINT `ingesta_fk`
    FOREIGN KEY (`ingestas_id`)
    REFERENCES `TAW`.`INGESTAS` (`ingestas_id`));


-- -----------------------------------------------------
-- Table `TAW`.`SESIONEJERCICIOCLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`SESIONEJERCICIOCLIENTE` ;

CREATE TABLE IF NOT EXISTS `TAW`.`SESIONEJERCICIOCLIENTE` (
  `sesion_ejercicio_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `feedback` VARCHAR(255) NULL DEFAULT NULL,
  `porcentaje_completado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sesion_ejercicio_id`, `usuario_id`),
  INDEX `usuario_fk_sesion_ejercicio` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `sesion_ejercicio_fk_cliente`
    FOREIGN KEY (`sesion_ejercicio_id`)
    REFERENCES `TAW`.`SESIONEJERCICIO` (`sesion_ejercicio_id`),
  CONSTRAINT `usuario_fk_sesion_ejercicio`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `TAW`.`USUARIO` (`usuario_id`));


-- -----------------------------------------------------
-- Table `TAW`.`REPETICION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`REPETICION` ;

CREATE TABLE IF NOT EXISTS `TAW`.`REPETICION` (
  `repeticiones_id` INT NOT NULL AUTO_INCREMENT,
  `sesion_ejercicio_id` INT NULL DEFAULT NULL,
  `numero_repeticion_asignado` INT NULL DEFAULT NULL,
  `numero_repeticion_completado` INT NULL DEFAULT NULL,
  `peso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`repeticiones_id`),
  INDEX `sesion_ejercicio_fk_repeticion` (`sesion_ejercicio_id` ASC) VISIBLE,
  CONSTRAINT `sesion_ejercicio_fk_repeticion`
    FOREIGN KEY (`sesion_ejercicio_id`)
    REFERENCES `TAW`.`SESIONEJERCICIO` (`sesion_ejercicio_id`));


-- -----------------------------------------------------
-- Table `TAW`.`DISTANCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`DISTANCIA` ;

CREATE TABLE IF NOT EXISTS `TAW`.`DISTANCIA` (
  `distancia_id` INT NOT NULL AUTO_INCREMENT,
  `sesion_ejercicio_id` INT NULL DEFAULT NULL,
  `distancia_km_asignado` INT NULL DEFAULT NULL,
  `distancia_km_completado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`distancia_id`),
  INDEX `sesion_ejercicio_fk_distancia` (`sesion_ejercicio_id` ASC) VISIBLE,
  CONSTRAINT `sesion_ejercicio_fk_distancia`
    FOREIGN KEY (`sesion_ejercicio_id`)
    REFERENCES `TAW`.`SESIONEJERCICIO` (`sesion_ejercicio_id`));


-- -----------------------------------------------------
-- Table `TAW`.`TIEMPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAW`.`TIEMPO` ;

CREATE TABLE IF NOT EXISTS `TAW`.`TIEMPO` (
  `tiempo_id` INT NOT NULL AUTO_INCREMENT,
  `sesion_ejercicio_id` INT NULL DEFAULT NULL,
  `tiempo_en_segundos_asignado` INT NULL DEFAULT NULL,
  `tiempo_en_segundos_completado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tiempo_id`),
  INDEX `sesion_ejercicio_fk_tiempo` (`sesion_ejercicio_id` ASC) VISIBLE,
  CONSTRAINT `sesion_ejercicio_fk_tiempo`
    FOREIGN KEY (`sesion_ejercicio_id`)
    REFERENCES `TAW`.`SESIONEJERCICIO` (`sesion_ejercicio_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;