INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (1, 'Push-ups', 'http://example.com/pushups', 1, 1);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (2, 'Squats', 'http://example.com/squats', 2, 2);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (3, 'Sit-ups', 'http://example.com/situps', 3, 3);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (4, 'Pull-ups', 'http://example.com/pullups', 4, 4);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (5, 'Bicep curls', 'http://example.com/bicepcurls', 5, 5);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (6, 'Push-ups', 'http://example.com/pushups', 1, 1);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (7, 'Squats', 'http://example.com/squats', 2, 2);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (8, 'Sit-ups', 'http://example.com/situps', 3, 3);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (9, 'Pull-ups', 'http://example.com/pullups', 4, 4);
INSERT INTO TAW.EJERCICIO (ejercicio_id, descripcion, url_video, grupo_muscular_id, categoria_id) VALUES (10, 'Bicep curls', 'http://example.com/bicepcurls', 5, 5);
